# Site settings
title: Alp Oran
job_title: Software Developer
cover: assets/images/cover.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/alporan/" # the subpath of your site, e.g. /blog/ or / for root
url: "" # the base hostname & protocol for your site

# Social
linkedin: https://www.linkedin.com/in/alp-oran
github:  https://github.com/alporan

#Additional Pages
about: about

permalink: /:title


# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml